import assert from 'node:assert/strict';
import test from 'node:test';
import { validateGeneratedChange } from './generated-config-validation.mjs';

for (const scenario of ['valid', 'unrelated', 'tampered', 'fork', 'other-branch', 'new-generator', 'deleted']) {
  test(`generated workflow trust: ${scenario}`, () => {
    const repository = 'mahn-ke/gdqreminder-by-vincent';
    const path = '.github/workflows/autogenerated-deploy.yml';
    const pr = { number: 1, head: { sha: 'a'.repeat(40), ref: scenario === 'other-branch' ? 'feature' : 'terraform/generated-config', repo: { full_name: scenario === 'fork' ? 'other/repo' : repository } } };
    let revisions = 0;
    const api = endpoint => {
      if (endpoint.endsWith('/commits/main')) return { sha: scenario === 'new-generator' && revisions++ ? 'c'.repeat(40) : 'b'.repeat(40) };
      return { content: Buffer.from(endpoint.includes('gdq-generated-files.json') ? JSON.stringify({ [path]: 'trusted bytes' }) : scenario === 'tampered' ? 'untrusted bytes' : 'trusted bytes').toString('base64') };
    };
    const pages = () => [{ filename: scenario === 'unrelated' ? 'app/index.js' : path, status: scenario === 'deleted' ? 'removed' : 'modified' }];
    if (scenario === 'valid') assert.equal(validateGeneratedChange(pr, repository, api, pages), 'b'.repeat(40));
    else assert.throws(() => validateGeneratedChange(pr, repository, api, pages));
  });
}