import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { evaluatePolicy } from './infrastructure-policy.mjs';
import { buildPonto, renderPlan } from './render-plan.mjs';

const repository = process.env.GITHUB_REPOSITORY;
if (repository !== 'mahn-ke/gdqreminder-by-vincent') throw new Error('GDQ pilot only');
const event = JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
const endpoint = `repos/${repository}`;
const marker = '<!-- infrastructure-review -->';
const cli = process.env.GH_BINARY || 'gh';
const invoke = args => execFileSync(cli, args, { encoding: 'utf8', timeout: 120000, maxBuffer: 16000000 });
function api(path, method = 'GET', body) {
  const args = ['api', path, '--method', method];
  if (body) args.push('--input', '-');
  return JSON.parse(execFileSync(cli, args, { input: body ? JSON.stringify(body) : undefined,
    encoding: 'utf8', timeout: 30000, maxBuffer: 16000000 }) || 'null');
}
function pages(path, property) {
  const result = JSON.parse(invoke(['api', path, '--paginate', '--slurp']));
  return result.flatMap(page => property ? page[property] : page);
}
function current(pr) {
  const fresh = api(`${endpoint}/pulls/${pr.number}`);
  if (fresh.state !== 'open' || fresh.head.sha !== pr.head.sha || fresh.base.sha !== pr.base.sha) {
    throw new Error('PR revision changed during policy evaluation');
  }
  return fresh;
}
function check(pr, conclusion, summary) {
  const existing = pages(`${endpoint}/commits/${pr.head.sha}/check-runs?per_page=100`, 'check_runs')
    .find(entry => entry.name === 'Infrastructure review' && entry.app.id === 15368);
  const body = { name: 'Infrastructure review', head_sha: pr.head.sha, status: 'completed', conclusion,
    output: { title: conclusion === 'success' ? 'Infrastructure policy satisfied' : 'Merge blocked', summary } };
  if (existing) return api(`${endpoint}/check-runs/${existing.id}`, 'PATCH', body);
  return api(`${endpoint}/check-runs`, 'POST', body);
}
function ownedComments(pr) {
  return pages(`${endpoint}/issues/${pr.number}/comments?per_page=100`)
    .filter(comment => comment.user.login === 'github-actions[bot]' && comment.body.startsWith(marker));
}
function textComment(pr, body) {
  current(pr);
  const existing = ownedComments(pr)[0];
  return existing ? api(`${endpoint}/issues/comments/${existing.id}`, 'PATCH', { body })
    : api(`${endpoint}/issues/${pr.number}/comments`, 'POST', { body });
}
let rendererReady = false;
async function processPR(pr) {
  check(pr, 'failure', 'Checking the latest build, both plans, and current-plan approval.');
  const directory = mkdtempSync(join(tmpdir(), 'infra-review-'));
  try {
    const main = api(`${endpoint}/commits/main`);
    if (main.sha !== pr.base.sha || pr.base.ref !== 'main') throw new Error('PR needs validation against current main');
    const runs = pages(`${endpoint}/actions/workflows/autogenerated-deploy.yml/runs?event=pull_request&head_sha=${pr.head.sha}&per_page=100`, 'workflow_runs')
      .sort((left, right) => right.id - left.id);
    const run = runs[0];
    if (!run) throw new Error('No validation run exists on this revision');
    const shared = api('repos/mahn-ke/.github/commits/main');
    if (!run.referenced_workflows?.some(workflow =>
      workflow.path === 'mahn-ke/.github/.github/workflows/template-deploy.yml@main' && workflow.sha === shared.sha)) {
      throw new Error('Validation must use the current trusted shared deployment workflow');
    }
    const workflowPath = '.github/workflows/autogenerated-deploy.yml';
    const headWorkflow = api(`${endpoint}/contents/${workflowPath}?ref=${pr.head.sha}`);
    const baseWorkflow = api(`${endpoint}/contents/${workflowPath}?ref=${pr.base.sha}`);
    if (headWorkflow.sha !== baseWorkflow.sha) throw new Error('Validate workflow changes through the generator before merging');
    const jobs = pages(`${endpoint}/actions/runs/${run.id}/jobs?filter=latest&per_page=100`, 'jobs');
    if (run.conclusion !== 'success' || run.status !== 'completed') throw new Error('Latest build or plan run is not successful');
    const artifacts = pages(`${endpoint}/actions/runs/${run.id}/artifacts?per_page=100`, 'artifacts');
    const reports = [];
    const plans = [];
    for (const root of ['infrastructure', 'service']) {
      const artifact = artifacts.filter(entry => entry.name === `plan-report-${root}`);
      if (artifact.length !== 1 || artifact[0].expired || artifact[0].size_in_bytes > 2000000) {
        throw new Error(`Missing or oversized ${root} report artifact`);
      }
      const target = join(directory, root);
      invoke(['run', 'download', String(run.id), '--repo', repository, '--name', `plan-report-${root}`, '--dir', target]);
      for (const name of ['report.json', 'plan.json']) {
        if (statSync(join(target, name)).size > 2000000) throw new Error('Oversized plan input');
      }
      reports.push(JSON.parse(readFileSync(join(target, 'report.json'), 'utf8')));
      plans.push(JSON.parse(readFileSync(join(target, 'plan.json'), 'utf8')));
    }
    const reviews = pages(`${endpoint}/pulls/${pr.number}/reviews?per_page=100`);
    const reviewers = [];
    for (const login of new Set(reviews.map(review => review.user.login))) {
      if (reviews.some(review => review.user.login === login && review.user.type === 'Bot')) continue;
      const permission = api(`${endpoint}/collaborators/${encodeURIComponent(login)}/permission`);
      if (['admin', 'maintain', 'write'].includes(permission.permission)) reviewers.push(login);
    }
    const result = evaluatePolicy({ pr, run, jobs, reports, reviews, reviewers });
    const bodyLines = [marker, '## Terraform Plan Review', '',
      `Revision: \`${pr.head.sha}\``, `Validation: ${run.html_url}`,
      `Plan digest: \`${result.digest}\``, '',
      result.changed ? 'Infrastructure changes detected. Automatic merging is disabled.' : 'Both plans report no changes.', ''];
    for (const report of reports) {
      bodyLines.push(`### ${report.root}`, '',
        `${report.resources.length} changed resources; ${report.outputChanges} changed outputs.`, '');
      if (report.resources.length) {
        bodyLines.push('| Resource | Actions |', '| --- | --- |',
          ...report.resources.map(resource => `| \`${resource.address}\` | ${resource.actions.join(', ')} |`), '');
      }
    }
    if (result.changed) bodyLines.push('Approve the current revision with an **Approve** review containing this exact line:', '',
      `\`Approve infrastructure plan ${result.digest}\``, '', 'Then merge manually after all required checks pass.', '');
    const existing = ownedComments(pr)[0];
    const revisionMarker = `<!-- plan-run:${run.id}:${run.run_attempt}:${result.digest} -->`;
    bodyLines.push(revisionMarker);
    if (!existing?.body.includes(revisionMarker)) {
      const images = [];
      if (result.changed && reports.some(report => report.resources.length)) {
        if (!invoke(['pr', 'comment', '--help']).includes('--attach')) {
          throw new Error('GitHub CLI 2.102.0 or newer with --attach is required');
        }
        if (reports.some(report => report.resources.length) && !process.env.PLAN_IMAGE_TOKEN) {
          throw new Error('PLAN_IMAGE_TOKEN is required for native image attachments; Actions tokens cannot upload');
        }
        if (!rendererReady) { buildPonto(); rendererReady = true; }
        for (let index = 0; index < reports.length; index++) {
          if (reports[index].exitcode !== 2 || !reports[index].resources.length) continue;
          const image = join(directory, `${reports[index].root}.png`);
          renderPlan(plans[index], reports[index], image);
          images.push(image);
          bodyLines.push('', `![${reports[index].root} resource graph](${image})`);
        }
      }
      current(pr);
      const body = bodyLines.join('\n');
      if (images.length) {
        const bodyFile = join(directory, 'comment.md');
        writeFileSync(bodyFile, body);
        const args = ['pr', 'comment', String(pr.number), '--repo', repository, '--body-file', bodyFile];
        for (const image of images) args.push('--attach', image);
        const uploadEnv = { PATH: process.env.PATH, HOME: process.env.HOME,
          GH_TOKEN: process.env.PLAN_IMAGE_TOKEN };
        const uploadOutput = execFileSync(cli, args,
          { env: uploadEnv, encoding: 'utf8', timeout: 120000 }).trim();
        const commentId = uploadOutput.match(/#issuecomment-(\d+)$/)?.[1];
        if (!commentId) throw new Error('Uploaded graph comment URL could not be verified');
        const uploaded = api(`${endpoint}/issues/comments/${commentId}`);
        if (!uploaded.body.startsWith(marker) || !uploaded.body.includes(revisionMarker)) {
          throw new Error('Uploaded graph comment did not match this plan');
        }
        textComment(pr, uploaded.body);
        execFileSync(cli, ['api', `${endpoint}/issues/comments/${commentId}`, '--method', 'DELETE'],
          { env: uploadEnv, encoding: 'utf8', timeout: 30000 });
      } else textComment(pr, body);
    }
    const fresh = current(pr);
    const latestRuns = api(`${endpoint}/actions/workflows/autogenerated-deploy.yml/runs?event=pull_request&head_sha=${pr.head.sha}&per_page=1`);
    if (latestRuns.workflow_runs[0]?.id !== run.id || latestRuns.workflow_runs[0]?.run_attempt !== run.run_attempt) {
      throw new Error('Validation was rerun while publishing; reevaluate the new plan');
    }
    const finalReviews = pages(`${endpoint}/pulls/${pr.number}/reviews?per_page=100`);
    const finalResult = evaluatePolicy({ pr: fresh, run, jobs, reports, reviews: finalReviews, reviewers });
    check(fresh, finalResult.allowed ? 'success' : 'failure', finalResult.changed
      ? finalResult.allowed ? 'Current-plan approval recorded. Merge manually; automerge remains disabled.'
        : `Human approval required for plan ${result.digest}. See the plan comment.`
      : 'Build and both plans succeeded without infrastructure changes.');
    if (finalResult.automerge && fresh.mergeable_state === 'clean') {
      api(`${endpoint}/pulls/${pr.number}/merge`, 'PUT', { sha: pr.head.sha, merge_method: 'rebase' });
    }
  } catch (error) {
    current(pr);
    check(pr, 'failure', String(error.message));
    textComment(pr, `${marker}\n## Terraform Plan Review\n\nMerge blocked: ${error.message}\n\nRevision: \`${pr.head.sha}\``);
    console.error(`PR #${pr.number}: ${error.message}`);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

let prs;
const number = event.pull_request?.number || (event.issue?.pull_request ? event.issue.number : undefined);
if (process.env.GITHUB_EVENT_NAME === 'issue_comment' && event.sender?.type === 'Bot') prs = [];
else if (number) prs = [api(`${endpoint}/pulls/${number}`)];
else prs = pages(`${endpoint}/pulls?state=open&per_page=100`);
for (const pr of prs.filter(pr => pr.state === 'open')) await processPR(pr);