import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { evaluatePolicy } from './infrastructure-policy.mjs';
import { validateGeneratedChange } from './generated-config-validation.mjs';

const repository = process.env.GITHUB_REPOSITORY;
if (repository !== 'mahn-ke/gdqreminder-by-vincent') throw new Error('GDQ pilot only');
const event = JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
const endpoint = `repos/${repository}`;
const cli = process.env.GH_BINARY || 'gh';
const invoke = (args, body) => JSON.parse(execFileSync(cli, args, {
  input: body ? JSON.stringify(body) : undefined,
  env: { ...process.env, GH_TOKEN: process.env.GITHUB_TOKEN || process.env.GH_TOKEN },
  encoding: 'utf8', timeout: 30000, maxBuffer: 16000000,
}) || 'null');
function api(path, method = 'GET', body) {
  const args = ['api', path, '--method', method];
  if (body) args.push('--input', '-');
  return invoke(args, body);
}
function pages(path, property) {
  const result = invoke(['api', path, '--paginate', '--slurp']);
  return result.flatMap(page => property ? page[property] : page);
}
function current(pr) {
  const fresh = api(`${endpoint}/pulls/${pr.number}`);
  return fresh.state === 'open' && fresh.head.sha === pr.head.sha && fresh.base.sha === pr.base.sha
    ? fresh : null;
}
function check(pr, conclusion, summary) {
  const existing = pages(`${endpoint}/commits/${pr.head.sha}/check-runs?per_page=100`, 'check_runs')
    .find(entry => entry.name === 'Infrastructure review' && entry.app.id === 15368);
  const body = { name: 'Infrastructure review', head_sha: pr.head.sha, status: 'completed', conclusion,
    output: { title: conclusion === 'success' ? 'Infrastructure policy satisfied' : 'Merge blocked', summary } };
  if (existing) return api(`${endpoint}/check-runs/${existing.id}`, 'PATCH', body);
  return api(`${endpoint}/check-runs`, 'POST', body);
}
function trusted(pr, run) {
  const main = api(`${endpoint}/commits/main`);
  if (main.sha !== pr.base.sha || pr.base.ref !== 'main') throw new Error('PR needs validation against current main');
  const shared = api('repos/mahn-ke/.github/commits/main');
  if (!run.referenced_workflows?.some(workflow =>
    workflow.path === 'mahn-ke/.github/.github/workflows/template-deploy.yml@main' && workflow.sha === shared.sha)) {
    throw new Error('Validation must use the current trusted shared deployment workflow');
  }
  const workflowPath = '.github/workflows/autogenerated-deploy.yml';
  const headWorkflow = api(`${endpoint}/contents/${workflowPath}?ref=${pr.head.sha}`);
  const baseWorkflow = api(`${endpoint}/contents/${workflowPath}?ref=${pr.base.sha}`);
  if (headWorkflow.sha !== baseWorkflow.sha) validateGeneratedChange(pr, repository, api, pages);
}
function latest(pr, run) {
  const runs = api(`${endpoint}/actions/workflows/autogenerated-deploy.yml/runs?event=pull_request&head_sha=${pr.head.sha}&per_page=1`);
  if (runs.workflow_runs[0]?.id !== run.id || runs.workflow_runs[0]?.run_attempt !== run.run_attempt) {
    throw new Error('Validation was rerun during policy evaluation');
  }
}
function processPR(pr) {
  try {
    if (!current(pr)) return;
    check(pr, 'failure', 'Checking the latest build and both plans.');
    const runs = pages(`${endpoint}/actions/workflows/autogenerated-deploy.yml/runs?event=pull_request&head_sha=${pr.head.sha}&per_page=100`, 'workflow_runs')
      .sort((left, right) => right.id - left.id);
    const run = runs[0];
    if (!run) throw new Error('No validation run exists on this revision');
    trusted(pr, run);
    const jobs = pages(`${endpoint}/actions/runs/${run.id}/jobs?filter=latest&per_page=100`, 'jobs');
    evaluatePolicy({ pr, run, jobs });
    const fresh = current(pr);
    if (!fresh) return;
    trusted(fresh, run);
    latest(fresh, run);
    const result = evaluatePolicy({ pr: fresh, run, jobs });
    check(fresh, 'success', result.changed
      ? 'Build and both plans succeeded. Merge manually; production environment approval is required before apply.'
      : 'Build and both plans succeeded without infrastructure changes.');
    if (result.automerge) {
      const mergePR = current(fresh);
      if (!mergePR) return;
      trusted(mergePR, run);
      latest(mergePR, run);
      if (evaluatePolicy({ pr: mergePR, run, jobs }).automerge && mergePR.mergeable_state === 'clean') {
        api(`${endpoint}/pulls/${pr.number}/merge`, 'PUT', { sha: mergePR.head.sha, merge_method: 'rebase' });
      }
    }
  } catch (error) {
    console.error(`PR #${pr.number}: ${error.message}`);
    try {
      if (current(pr)) check(pr, 'failure', String(error.message));
    } catch (failure) {
      console.error(`PR #${pr.number}: ${failure.message}`);
    }
  }
}

let prs;
const number = event.pull_request?.number || (event.issue?.pull_request ? event.issue.number : undefined);
if (process.env.GITHUB_EVENT_NAME === 'issue_comment' && event.sender?.type === 'Bot') prs = [];
else if (number) prs = [api(`${endpoint}/pulls/${number}`)];
else prs = pages(`${endpoint}/pulls?state=open&per_page=100`);
for (const pr of prs.filter(pr => pr.state === 'open')) processPR(pr);