import assert from 'node:assert/strict';
import test from 'node:test';
import { marker, runReporter, validateArtifact } from './plan-comment.mjs';

function fixture(scenario = 'changed') {
  const repository = 'mahn-ke/repos';
  const pr = { number: 15, state: 'open', head: { sha: 'a'.repeat(40), repo: { full_name: repository } }, base: { sha: 'b'.repeat(40), ref: 'main' } };
  const run = { id: 123, run_attempt: 2, path: '.github/workflows/autogenerated-deploy.yml', head_sha: pr.head.sha,
    event: scenario === 'main' ? 'push' : 'pull_request', status: 'completed', pull_requests: [pr],
    referenced_workflows: [{ path: 'mahn-ke/.github/.github/workflows/template-deploy.yml@main', sha: 'c'.repeat(40) }] };
  const writes = [];
  const image = Buffer.alloc(128);
  Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).copy(image);
  let reads = 0;
  const options = { repository, runId: 123, attempt: 2,
    api(endpoint, method = 'GET', body) {
      if (method !== 'GET') { writes.push({ endpoint, method, body }); return {}; }
      if (endpoint.endsWith('/pulls/15')) {
        reads++;
        return scenario === 'stale' || (scenario === 'race' && reads > 2) ? { ...pr, head: { ...pr.head, sha: 'd'.repeat(40) } } : pr;
      }
      if (endpoint.endsWith('/runs/123')) return run;
      if (endpoint.includes('/runs?')) return { workflow_runs: [{ ...run, id: scenario === 'new-run' ? 124 : 123 }] };
      if (endpoint === 'repos/mahn-ke/.github/commits/main') return { sha: scenario === 'untrusted' ? 'd'.repeat(40) : 'c'.repeat(40) };
      if (endpoint.endsWith('/commits/main')) return { sha: pr.base.sha };
      if (endpoint.includes('/contents/')) return { sha: scenario === 'wrapper' && endpoint.endsWith(pr.head.sha) ? 'changed' : 'same' };
      throw new Error(`Unexpected endpoint: ${endpoint}`);
    },
    pages(endpoint) {
      if (endpoint.includes('/jobs?')) return ['infrastructure', 'service'].map(root => ({
        name: `deploy / ${root}-terraform-plan`, conclusion: scenario === 'partial' && root === 'service' ? 'failure' : 'success',
        steps: [{ name: scenario === 'no-change' ? 'No Terraform changes' : 'Terraform changes detected', conclusion: 'success' }] }));
      if (endpoint.includes('/artifacts?')) return scenario === 'missing' ? [] : ['infrastructure', 'service'].map((root, index) => ({ id: index + 1, name: `terraform-plan-image-${root}`, size_in_bytes: 1000 }));
      if (endpoint.includes('/comments?')) return scenario === 'existing' ? [{ id: 9, user: { login: 'github-actions[bot]' }, body: `${marker}\nold image` }] : [];
      throw new Error(`Unexpected page endpoint: ${endpoint}`);
    },
    download(artifact, root) {
      return { image, report: { version: 1, root, exitcode: 2, headSha: pr.head.sha, baseSha: pr.base.sha, runId: '123', runAttempt: scenario === 'old-attempt' ? '1' : '2', digest: 'e'.repeat(64) } };
    },
    upload: scenario === 'inline' ? () => 'https://github.com/user-attachments/assets/abc' : undefined,
  };
  return { options, writes, pr, run, image };
}

for (const scenario of ['changed', 'existing', 'inline', 'no-change', 'partial']) {
  test(`PR reporter: ${scenario}`, () => {
    const { options, writes } = fixture(scenario);
    assert.equal(runReporter(options), 'published');
    assert.equal(writes.length, 1);
    assert.equal(writes[0].method, scenario === 'existing' ? 'PATCH' : 'POST');
    assert.ok(writes[0].body.body.startsWith(marker));
    if (scenario === 'inline') assert.match(writes[0].body.body, /!\[Infrastructure Terraform plan\]/);
    if (scenario === 'changed') assert.match(writes[0].body.body, /Download PNG artifact/);
    if (scenario === 'no-change') assert.doesNotMatch(writes[0].body.body, /!\[|Download PNG/);
    if (scenario === 'partial') assert.match(writes[0].body.body, /did not succeed/);
  });
}
for (const scenario of ['main', 'stale', 'race', 'new-run']) {
  test(`PR reporter never publishes: ${scenario}`, () => {
    const { options, writes } = fixture(scenario);
    assert.ok(['skipped', 'stale'].includes(runReporter(options)));
    assert.deepEqual(writes, []);
  });
}
for (const scenario of ['untrusted', 'wrapper', 'missing', 'old-attempt']) {
  test(`PR reporter rejects: ${scenario}`, () => {
    const { options, writes } = fixture(scenario);
    assert.throws(() => runReporter(options));
    assert.deepEqual(writes, []);
  });
}
test('invalid or oversized PNG is rejected', () => {
  const { options, pr, run } = fixture();
  const report = options.download({}, 'infrastructure').report;
  assert.throws(() => validateArtifact(report, Buffer.alloc(128), 'infrastructure', pr, run));
  assert.throws(() => validateArtifact(report, Buffer.alloc(10000001), 'infrastructure', pr, run));
});