import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export const marker = '<!-- mahn-ke-terraform-plan-images -->';
const roots = ['infrastructure', 'service'];
const pngSignature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

export function validateArtifact(report, image, root, pr, run) {
  if (report.version !== 1 || report.root !== root || report.exitcode !== 2
      || report.headSha !== pr.head.sha || report.baseSha !== pr.base.sha
      || report.runId !== String(run.id) || report.runAttempt !== String(run.run_attempt)
      || !/^[a-f0-9]{64}$/.test(report.digest)) throw new Error('Plan image provenance mismatch');
  if (image.length < 100 || image.length > 10000000 || !image.subarray(0, 8).equals(pngSignature)) {
    throw new Error('Invalid plan PNG');
  }
}

export function runReporter({ repository, runId, attempt, api, pages, download, upload }) {
  if (!/^mahn-ke\/[A-Za-z0-9_.-]+$/.test(repository)) throw new Error('Managed repositories only');
  if (!/^\d+$/.test(String(runId)) || !/^[1-9]\d*$/.test(String(attempt))) throw new Error('Invalid run identity');
  const endpoint = `repos/${repository}`;
  const run = api(`${endpoint}/actions/runs/${runId}`);
  if (run.event !== 'pull_request' || run.status !== 'completed' || run.run_attempt !== Number(attempt)) return 'skipped';
  if (run.path !== '.github/workflows/autogenerated-deploy.yml') throw new Error('Unexpected producer workflow');
  const shared = api('repos/mahn-ke/.github/commits/main');
  if (!run.referenced_workflows?.some(workflow =>
    workflow.path === 'mahn-ke/.github/.github/workflows/template-deploy.yml@main' && workflow.sha === shared.sha)) {
    throw new Error('Untrusted producer workflow revision');
  }
  const matches = (run.pull_requests || []).filter(pr => pr.head.sha === run.head_sha);
  if (matches.length !== 1) return 'skipped';
  const number = matches[0].number;
  const pr = api(`${endpoint}/pulls/${number}`);
  function fresh() {
    const current = api(`${endpoint}/pulls/${number}`);
    const latest = api(`${endpoint}/actions/workflows/autogenerated-deploy.yml/runs?event=pull_request&head_sha=${pr.head.sha}&per_page=1`).workflow_runs[0];
    const rerun = api(`${endpoint}/actions/runs/${runId}`);
    return current.state === 'open' && current.head.repo?.full_name === repository
      && current.base.ref === 'main' && current.head.sha === run.head_sha
      && current.base.sha === pr.base.sha && api(`${endpoint}/commits/main`).sha === pr.base.sha
      && latest?.id === run.id && latest.run_attempt === run.run_attempt
      && rerun.run_attempt === run.run_attempt && rerun.status === 'completed';
  }
  if (!fresh()) return 'stale';
  const wrapper = '.github/workflows/autogenerated-deploy.yml';
  if (api(`${endpoint}/contents/${wrapper}?ref=${pr.head.sha}`).sha
      !== api(`${endpoint}/contents/${wrapper}?ref=${pr.base.sha}`).sha) throw new Error('Producer wrapper changed in PR');
  const jobs = pages(`${endpoint}/actions/runs/${runId}/attempts/${attempt}/jobs?per_page=100`, 'jobs');
  const artifacts = pages(`${endpoint}/actions/runs/${runId}/artifacts?per_page=100`, 'artifacts');
  const sections = [];
  for (const root of roots) {
    const job = jobs.find(entry => entry.name === `deploy / ${root}-terraform-plan`);
    const heading = root === 'infrastructure' ? 'Infrastructure' : 'Service';
    if (!job || job.conclusion !== 'success') {
      sections.push(`### ${heading}\nPlan validation did not succeed; no current image is published.`);
      continue;
    }
    if (job.steps?.some(step => step.name === 'No Terraform changes' && step.conclusion === 'success')) {
      sections.push(`### ${heading}\nNo Terraform changes.`);
      continue;
    }
    if (!job.steps?.some(step => step.name === 'Terraform changes detected' && step.conclusion === 'success')) {
      throw new Error(`Cannot determine ${root} plan result`);
    }
    const candidates = artifacts.filter(entry => entry.name === `terraform-plan-image-${root}` && !entry.expired);
    if (candidates.length !== 1) throw new Error(`Missing or ambiguous ${root} PNG artifact`);
    const artifact = candidates[0];
    if (!Number.isSafeInteger(artifact.id) || artifact.size_in_bytes > 11000000) throw new Error('Invalid artifact size or identity');
    const { report, image } = download(artifact, root);
    validateArtifact(report, image, root, pr, run);
    let imageUrl;
    if (fresh()) imageUrl = upload?.({ image, root, number, run });
    const artifactUrl = `https://github.com/${repository}/actions/runs/${run.id}/artifacts/${artifact.id}`;
    sections.push(`### ${heading}\n${imageUrl ? `![${heading} Terraform plan](${imageUrl})\n\n` : 'Inline attachment unavailable; download the PNG below.\n\n'}[Download PNG artifact](${artifactUrl})`);
  }
  const body = `${marker}\n## Terraform Plans\n\n[Validation run ${run.id}, attempt ${run.run_attempt}](https://github.com/${repository}/actions/runs/${run.id})\n\nHead: \`${pr.head.sha}\`\nBase: \`${pr.base.sha}\`\n\n${sections.join('\n\n')}`;
  if (!fresh()) return 'stale';
  const comments = pages(`${endpoint}/issues/${number}/comments?per_page=100`);
  const existing = comments.find(comment => comment.user?.login === 'github-actions[bot]' && comment.body?.startsWith(marker));
  if (existing) api(`${endpoint}/issues/comments/${existing.id}`, 'PATCH', { body });
  else api(`${endpoint}/issues/${number}/comments`, 'POST', { body });
  return 'published';
}

function cli(args, token = process.env.GH_TOKEN, options = {}) {
  return execFileSync(process.env.GH_BINARY || 'gh', args, {
    env: { ...process.env, GH_TOKEN: token }, timeout: 120000,
    maxBuffer: 12000000, stdio: ['pipe', 'pipe', 'pipe'], ...options,
  });
}

function request(endpoint, method = 'GET', body, token) {
  const args = ['api', endpoint, '--method', method];
  if (body) args.push('--input', '-');
  return JSON.parse(cli(args, token, { input: body ? JSON.stringify(body) : undefined }).toString() || 'null');
}

export function downloadArtifact(repository, artifact, root) {
  const directory = mkdtempSync(join(tmpdir(), 'plan-comment-'));
  try {
    const archive = join(directory, 'artifact.zip');
    writeFileSync(archive, cli(['api', `repos/${repository}/actions/artifacts/${artifact.id}/zip`]));
    const names = execFileSync('unzip', ['-Z1', archive], { encoding: 'utf8', maxBuffer: 4096 }).trim().split('\n').sort();
    if (JSON.stringify(names) !== JSON.stringify([`${root}.png`, 'report.json'].sort())) throw new Error('Unexpected archive entries');
    const report = JSON.parse(execFileSync('unzip', ['-p', archive, 'report.json'], { maxBuffer: 1000000 }).toString());
    const image = execFileSync('unzip', ['-p', archive, `${root}.png`], { maxBuffer: 10000000 });
    return { report, image };
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

export function uploadImage(repository, { image, root, number, run }) {
  const tokens = [...new Set([process.env.PLAN_IMAGE_TOKEN, process.env.RENOVATE_TOKEN, process.env.TF_VAR_GITHUB_PAT].filter(Boolean))];
  if (!tokens.length) return undefined;
  const directory = mkdtempSync(join(tmpdir(), 'plan-attachment-'));
  const path = join(directory, `${root}.png`);
  writeFileSync(path, image);
  try {
    for (const token of tokens) {
      let commentId;
      try {
        const result = cli(['pr', 'comment', String(number), '--repo', repository,
          '--body', `<!-- mahn-ke-plan-image-upload:${run.id}:${run.run_attempt}:${root} -->`,
          '--attach', `${path}#${root} Terraform plan`], token).toString().trim();
        const match = result.match(new RegExp(`^https://github\\.com/${repository}/pull/${number}#issuecomment-(\\d+)$`));
        if (!match) throw new Error('Unexpected upload response');
        commentId = match[1];
        const comment = request(`repos/${repository}/issues/comments/${commentId}`, 'GET', undefined, token);
        const url = comment.body?.match(/https:\/\/github\.com\/user-attachments\/assets\/[a-f0-9-]+/i)?.[0];
        if (!url) throw new Error('Missing uploaded image URL');
        return url;
      } catch {
        console.warn('PNG attachment upload unavailable; trying next configured token or artifact-link fallback.');
      } finally {
        if (commentId) {
          try { request(`repos/${repository}/issues/comments/${commentId}`, 'DELETE', undefined, token); }
          catch { console.warn('Temporary attachment comment cleanup failed.'); }
        }
      }
    }
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
  return undefined;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const repository = process.env.GITHUB_REPOSITORY;
  console.log(runReporter({ repository, runId: process.env.PLAN_RUN_ID, attempt: process.env.PLAN_RUN_ATTEMPT,
    api: request,
    pages(endpoint, property) {
      const result = JSON.parse(cli(['api', endpoint, '--paginate', '--slurp']).toString());
      return result.flatMap(page => property ? page[property] : page);
    },
    download: (artifact, root) => downloadArtifact(repository, artifact, root),
    upload: options => uploadImage(repository, options),
  }));
}