name: Backup volumes from docker-compose.yml

on:
  workflow_call:

concurrency:
  group: backup-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backup:
    uses: mahn-ke/.github/.github/workflows/backup.yml@main
    secrets: inherit
